version: '3'

services:
  my-postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    # network_mode: "host"
    networks:
      - mynetwork2
    volumes:
      - postgra:/var/lib/postgresql/data
  my-postgres-test-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    # network_mode: "host"
    networks:
      - mynetwork2
    volumes:
      - postgra-test:/var/lib/postgresql/data

networks:
  mynetwork2:
volumes:
  postgra:
  postgra-test:
